import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Wand2, Copy, Download } from "lucide-react";
import { toast } from "sonner";

const PROVIDERS = ["aws", "azure", "gcp", "kubernetes"];
const RESOURCES = {
  aws: ["VPC", "EC2", "RDS", "S3", "Lambda", "API Gateway", "CloudFront", "ECS"],
  azure: ["Virtual Network", "VM", "SQL Database", "Storage Account", "Functions", "App Service"],
  gcp: ["VPC", "Compute Engine", "Cloud SQL", "Cloud Storage", "Cloud Functions", "GKE"],
  kubernetes: ["Deployment", "Service", "Ingress", "ConfigMap", "Secret", "PersistentVolume"]
};

export default function TerraformGenerator({ open, onClose, onGenerate }) {
  const [projectName, setProjectName] = useState("");
  const [provider, setProvider] = useState("aws");
  const [region, setRegion] = useState("us-east-1");
  const [selectedResources, setSelectedResources] = useState([]);
  const [generatedCode, setGeneratedCode] = useState("");
  const [environment, setEnvironment] = useState("production");

  const toggleResource = (resource) => {
    setSelectedResources(prev =>
      prev.includes(resource)
        ? prev.filter(r => r !== resource)
        : [...prev, resource]
    );
  };

  const generateTerraformCode = () => {
    if (!projectName.trim()) {
      toast.error("Please enter a project name");
      return;
    }

    if (selectedResources.length === 0) {
      toast.error("Please select at least one resource");
      return;
    }

    let code = `# Generated by CloudForge Infrastructure Generator
# Project: ${projectName}
# Provider: ${provider}
# Environment: ${environment}

terraform {
  required_providers {
    ${provider} = {
      source  = "hashicorp/${provider}"
      version = "~> 5.0"
    }
  }
}

provider "${provider}" {
  region = "${region}"
}

`;

    // Generate code based on selected resources
    if (provider === "aws") {
      if (selectedResources.includes("VPC")) {
        code += `resource "aws_vpc" "${projectName}_vpc" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name        = "${projectName}-vpc"
    Environment = "${environment}"
  }
}

resource "aws_subnet" "${projectName}_subnet" {
  vpc_id                  = aws_vpc.${projectName}_vpc.id
  cidr_block              = "10.0.1.0/24"
  availability_zone       = "${region}a"
  map_public_ip_on_launch = true

  tags = {
    Name        = "${projectName}-subnet"
    Environment = "${environment}"
  }
}

resource "aws_internet_gateway" "${projectName}_igw" {
  vpc_id = aws_vpc.${projectName}_vpc.id

  tags = {
    Name        = "${projectName}-igw"
    Environment = "${environment}"
  }
}

`;
      }

      if (selectedResources.includes("EC2")) {
        code += `resource "aws_instance" "${projectName}_instance" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t3.micro"
  subnet_id     = aws_subnet.${projectName}_subnet.id

  tags = {
    Name        = "${projectName}-instance"
    Environment = "${environment}"
  }
}

`;
      }

      if (selectedResources.includes("RDS")) {
        code += `resource "aws_db_instance" "${projectName}_db" {
  identifier           = "${projectName}-db"
  engine               = "postgres"
  engine_version       = "15.3"
  instance_class       = "db.t3.micro"
  allocated_storage    = 20
  db_name              = "${projectName.replace(/-/g, '_')}"
  username             = "admin"
  password             = "changeme123"
  skip_final_snapshot  = true

  tags = {
    Name        = "${projectName}-db"
    Environment = "${environment}"
  }
}

`;
      }

      if (selectedResources.includes("S3")) {
        code += `resource "aws_s3_bucket" "${projectName}_bucket" {
  bucket = "${projectName}-${environment}-bucket"

  tags = {
    Name        = "${projectName}-bucket"
    Environment = "${environment}"
  }
}

resource "aws_s3_bucket_versioning" "${projectName}_bucket_versioning" {
  bucket = aws_s3_bucket.${projectName}_bucket.id

  versioning_configuration {
    status = "Enabled"
  }
}

`;
      }
    }

    code += `# Outputs
output "project_name" {
  value = "${projectName}"
}

output "environment" {
  value = "${environment}"
}
`;

    setGeneratedCode(code);
    toast.success("Terraform code generated successfully");
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    toast.success("Code copied to clipboard");
  };

  const handleDownload = () => {
    const blob = new Blob([generatedCode], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${projectName}-infrastructure.tf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Terraform file downloaded");
  };

  const handleSaveAsTemplate = () => {
    onGenerate({
      name: projectName,
      description: `Generated infrastructure for ${projectName}`,
      provider: provider.toUpperCase(),
      code: generatedCode,
      resources: selectedResources,
      isCustom: true
    });
    toast.success("Saved as custom template");
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-6xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-3">
            <Wand2 className="w-5 h-5 text-violet-600" />
            Generate Terraform Boilerplate
          </DialogTitle>
        </DialogHeader>

        <div className="grid grid-cols-2 gap-6 mt-4">
          {/* Configuration */}
          <div className="space-y-4">
            <div>
              <Label>Project Name</Label>
              <Input
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                placeholder="my-project"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label>Provider</Label>
                <Select value={provider} onValueChange={setProvider}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {PROVIDERS.map(p => (
                      <SelectItem key={p} value={p}>{p.toUpperCase()}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label>Environment</Label>
                <Select value={environment} onValueChange={setEnvironment}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="development">Development</SelectItem>
                    <SelectItem value="staging">Staging</SelectItem>
                    <SelectItem value="production">Production</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div>
              <Label>Region</Label>
              <Input
                value={region}
                onChange={(e) => setRegion(e.target.value)}
                placeholder="us-east-1"
              />
            </div>

            <div>
              <Label className="mb-3 block">Select Resources</Label>
              <div className="space-y-2 max-h-60 overflow-y-auto">
                {RESOURCES[provider]?.map(resource => (
                  <div key={resource} className="flex items-center gap-3">
                    <Checkbox
                      id={resource}
                      checked={selectedResources.includes(resource)}
                      onCheckedChange={() => toggleResource(resource)}
                    />
                    <label
                      htmlFor={resource}
                      className="text-sm font-medium cursor-pointer"
                    >
                      {resource}
                    </label>
                  </div>
                ))}
              </div>
            </div>

            <Button
              onClick={generateTerraformCode}
              className="w-full bg-violet-600 hover:bg-violet-700"
            >
              <Wand2 className="w-4 h-4 mr-2" /> Generate Code
            </Button>
          </div>

          {/* Generated Code Preview */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <Label>Generated Code</Label>
              {generatedCode && (
                <div className="flex gap-2">
                  <Button size="sm" variant="outline" onClick={handleCopy}>
                    <Copy className="w-3 h-3 mr-1" /> Copy
                  </Button>
                  <Button size="sm" variant="outline" onClick={handleDownload}>
                    <Download className="w-3 h-3 mr-1" /> Download
                  </Button>
                </div>
              )}
            </div>
            <div className="bg-slate-900 rounded-lg p-4 h-[500px] overflow-y-auto">
              {generatedCode ? (
                <pre className="text-sm text-slate-100">
                  <code>{generatedCode}</code>
                </pre>
              ) : (
                <div className="h-full flex items-center justify-center text-slate-500">
                  Configure your infrastructure and click Generate Code
                </div>
              )}
            </div>
            {generatedCode && (
              <Button
                onClick={handleSaveAsTemplate}
                variant="outline"
                className="w-full"
              >
                Save as Custom Template
              </Button>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}